<a href="https://colab.research.google.com/github/krishn-stack/Introduction_to_PyTorch/blob/main/My_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
from torch import nn

In [5]:
class LogisticRegression(nn.Module):
  def __init__(self, insize):
      super().__init__()
      self.log_reg = nn.Sequential(
      nn.Linear(insize,1),
      nn.Sigmoid()
    )
  def forward(self,x):
    return self.log_reg(x)


In [6]:
model = LogisticRegression(16)
criterion = nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(),lr=0.01)

**Introduction to PyTorch Framework**

In [7]:
import torch
from torch import nn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [8]:
example_tensor = torch.Tensor(
    [
        [[1,2],[3,4]],
        [[5,6],[7,8]],
        [[9,0],[1,2]]
    ]
)
example_tensor

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]],

        [[9., 0.],
         [1., 2.]]])

In [9]:
new_tensor = example_tensor.to(device = 'cpu')
new_tensor.device

device(type='cpu')

In [10]:
print("Shape = ",example_tensor.shape)
print("Size(0) = ",example_tensor.size(0))
print("Shape[0] = ",example_tensor.shape[1])

Shape =  torch.Size([3, 2, 2])
Size(0) =  3
Shape[0] =  2


In [11]:
print("Rank = ",len(example_tensor.shape))
print("Number of elements = ",example_tensor.numel())

Rank =  3
Number of elements =  12


In [12]:
example_scaler = example_tensor[1,1,1]
example_scaler.item()

8.0

In [13]:
example_tensor[1,1,0]

tensor(7.)

In [14]:
(example_tensor - 5)*2

tensor([[[ -8.,  -6.],
         [ -4.,  -2.]],

        [[  0.,   2.],
         [  4.,   6.]],

        [[  8., -10.],
         [ -8.,  -6.]]])

In [15]:
print("Mean:",example_tensor.mean())
print("Stdev:",example_tensor.std())

Mean: tensor(4.)
Stdev: tensor(2.9848)


In [16]:
example_tensor.mean(0)

# example_tensor.mean(dim=0)
# example_tensor.mean(axis=0)
# torch.mean(example.tensor,0)
# torch.mean(example_tensor,dim=0)
# torch.mean(example_tensor,axis=0)

tensor([[5.0000, 2.6667],
        [3.6667, 4.6667]])

In [17]:
import torch.nn as nn

In [18]:
linear = nn.Linear(10,2)
example_input = torch.randn(3,10)
example_output = linear(example_input)
example_output

tensor([[ 0.4715, -0.4913],
        [ 0.1317,  0.0790],
        [ 1.5622, -0.5078]], grad_fn=<AddmmBackward0>)

In [19]:
relu = nn.ReLU()
relu_output = relu(example_output)
relu_output

tensor([[0.4715, 0.0000],
        [0.1317, 0.0790],
        [1.5622, 0.0000]], grad_fn=<ReluBackward0>)

In [20]:
batchnorm = nn.BatchNorm1d(2)
batchnorm_output = batchnorm(relu_output)
batchnorm_output

tensor([[-0.4102, -0.7046],
        [-0.9670,  1.4091],
        [ 1.3772, -0.7046]], grad_fn=<NativeBatchNormBackward0>)

In [21]:
mlp_layer = nn.Sequential(
    nn.Linear(5,2),
    nn.BatchNorm1d(2),
    nn.ReLU()
)

test_example = torch.randn(5,5)+1
print("input:",test_example)
print("output:",mlp_layer(test_example))

input: tensor([[ 1.8776,  0.3865, -0.0887,  2.3995,  0.7662],
        [ 1.5357,  0.4167,  0.1889,  1.4011, -0.7588],
        [ 1.4350,  2.8518,  0.3845,  0.4815,  0.4338],
        [-0.0971,  0.1707,  0.9127,  1.1419,  0.3936],
        [ 0.9433,  2.1954,  0.3363,  0.7991,  1.3530]])
output: tensor([[0.8052, 0.0000],
        [1.0143, 1.7279],
        [0.0000, 0.0000],
        [0.6065, 0.2303],
        [0.0000, 0.0000]], grad_fn=<ReluBackward0>)


In [22]:
import torch.optim as optim
adam_opt = optim.Adam(mlp_layer.parameters(),lr = 1e-1)

In [23]:
adam_opt

Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    capturable: False
    decoupled_weight_decay: False
    differentiable: False
    eps: 1e-08
    foreach: None
    fused: None
    lr: 0.1
    maximize: False
    weight_decay: 0
)

In [24]:
train_example = torch.randn(100,5)+1
adam_opt.zero_grad()
cur_loss = torch.abs(1-mlp_layer(train_example)).mean()
cur_loss.backward()
adam_opt.step()
print(cur_loss)

tensor(0.7828, grad_fn=<MeanBackward0>)


In [25]:
class ExampleModule(nn.Module):
    def __init__(self, input_dims, output_dims):
        super(ExampleModule, self).__init__()
        self.linear = nn.Linear(input_dims, output_dims)
        self.exponent = nn.Parameter(torch.tensor(1.))

    def forward(self, x):
        x = self.linear(x)

        # This is the notation for element-wise exponentiation,
        # which matches python in general
        x = x ** self.exponent

        return x

In [26]:
example_model = ExampleModule(10, 2)
list(example_model.parameters())

[Parameter containing:
 tensor(1., requires_grad=True),
 Parameter containing:
 tensor([[ 0.1614,  0.2083,  0.1891,  0.0820,  0.0916, -0.1290,  0.1301,  0.0603,
           0.1622,  0.2297],
         [ 0.1187,  0.2428, -0.0035,  0.3063, -0.1950,  0.2933,  0.2160,  0.2932,
           0.2785,  0.2497]], requires_grad=True),
 Parameter containing:
 tensor([0.0534, 0.2326], requires_grad=True)]

In [27]:
list(example_model.named_parameters())

[('exponent',
  Parameter containing:
  tensor(1., requires_grad=True)),
 ('linear.weight',
  Parameter containing:
  tensor([[ 0.1614,  0.2083,  0.1891,  0.0820,  0.0916, -0.1290,  0.1301,  0.0603,
            0.1622,  0.2297],
          [ 0.1187,  0.2428, -0.0035,  0.3063, -0.1950,  0.2933,  0.2160,  0.2932,
            0.2785,  0.2497]], requires_grad=True)),
 ('linear.bias',
  Parameter containing:
  tensor([0.0534, 0.2326], requires_grad=True))]

In [28]:
input = torch.randn(2, 10)
example_model(input)

tensor([[-0.0550, -0.8236],
        [-0.0098, -0.8293]], grad_fn=<PowBackward1>)