In [2]:
import torch
from torch import nn

In [12]:
class LogisticRegression(nn.Module):
  def __init__(self, insize):
      super().__init__()
      self.log_reg = nn.Sequential(
      nn.Linear(insize,1),
      nn.Sigmoid()
    )
  def forward(self,x):
    return self.log_reg(x)


In [13]:
model = LogisticRegression(16)
criterion = nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(),lr=0.01)

In [17]:
from re import X
n_epochs = 100
for t in range(n_epochs):
  y_pred = model(x)
  loss = criterion(y_pred, y)
  optimizer.zero_grad()
  loss.backward()
  optimizer.step()

NameError: name 'x' is not defined

**Introduction to PyTorch Framework**

In [1]:
import torch
from torch import nn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
example_tensor = torch.Tensor(
    [
        [[1,2],[3,4]],
        [[5,6],[7,8]],
        [[9,0],[1,2]]
    ]
)
example_tensor

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]],

        [[9., 0.],
         [1., 2.]]])

In [9]:
new_tensor = example_tensor.to(device = 'cpu')
new_tensor.device

device(type='cpu')

In [17]:
print("Shape = ",example_tensor.shape)
print("Size(0) = ",example_tensor.size(0))
print("Shape[0] = ",example_tensor.shape[1])

Shape =  torch.Size([3, 2, 2])
Size(0) =  3
Shape[0] =  2


In [18]:
print("Rank = ",len(example_tensor.shape))
print("Number of elements = ",example_tensor.numel())

Rank =  3
Number of elements =  12


In [24]:
example_scaler = example_tensor[1,1,1]
example_scaler.item()

8.0

In [26]:
example_tensor[1,1,0]

tensor(7.)

In [27]:
(example_tensor - 5)*2

tensor([[[ -8.,  -6.],
         [ -4.,  -2.]],

        [[  0.,   2.],
         [  4.,   6.]],

        [[  8., -10.],
         [ -8.,  -6.]]])

In [28]:
print("Mean:",example_tensor.mean())
print("Stdev:",example_tensor.std())

Mean: tensor(4.)
Stdev: tensor(2.9848)


In [34]:
example_tensor.mean(0)

# example_tensor.mean(dim=0)
# example_tensor.mean(axis=0)
# torch.mean(example.tensor,0)
# torch.mean(example_tensor,dim=0)
# torch.mean(example_tensor,axis=0)

tensor([[5.0000, 2.6667],
        [3.6667, 4.6667]])